import { builtinModules } from 'node:module';
import path from 'node:path';
import process from 'node:process';
import esbuild from 'esbuild';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const mode = process.argv[2];
const isProd = mode === 'production';
const isWatch = mode === 'watch';

const ollamaBrowserPath = path.resolve('node_modules/ollama/dist/browser.mjs');

const buildOptions = {
    banner: {
        js: banner,
    },
    entryPoints: ['src/main.ts'],
    bundle: true,
    alias: {
        ollama: ollamaBrowserPath,
    },
    external: [
        'obsidian',
        'electron',
        '@codemirror/autocomplete',
        '@codemirror/collab',
        '@codemirror/commands',
        '@codemirror/language',
        '@codemirror/lint',
        '@codemirror/search',
        '@codemirror/state',
        '@codemirror/view',
        '@lezer/common',
        '@lezer/highlight',
        '@lezer/lr',
        ...builtinModules,
    ],
    format: 'cjs',
    target: 'es2022',
    logLevel: 'info',
    sourcemap: isProd ? false : 'inline',
    treeShaking: true,
    outfile: 'main.js',
    minify: isProd,
    define: {
        'process.env.NODE_ENV': JSON.stringify(
            isProd ? 'production' : 'development',
        ),
    },
    drop: isProd ? ['console', 'debugger'] : [],
};

if (isWatch) {
    const context = await esbuild.context(buildOptions);
    await context.watch();
    console.debug('Watching for changes...');
} else {
    await esbuild.build(buildOptions);
    console.debug(`${isProd ? 'Production' : 'Development'} build complete.`);
    process.exit(0);
}
